theme: jekyll-theme-cayman
title:        Loïs Bilat
description:      Computer Science Student
url:          "https://bilat.xyz"
baseurl:      ""
paginate:     1
locale:       "en"
google_analytics: UA-58165571-2

# About/contact
author:
  name:       Loïs Bilat
  url:        https://bilat.xyz 

github:
  is_project_page: false

show_downloads: true
footer: © Copyright 2019 - Loïs Bilat - <a href="https://bilat.xyz">bilat.xyz</a>
buttons:
  url_btn_1: https://cv.bilat.xyz
  url_btn_2: https://git.bilat.xyz
  text_btn_1: CV
  text_btn_2: GitHub
