theme: jekyll-theme-cayman
title:        Loïs Bilat
# description:      Computer Science Student
url:          "https://bilat.xyz"
baseurl:      ""
paginate:     1
locale:       "en"
google_analytics: UA-58165571-2

# About/contact
author:
  name:       Loïs Bilat
  url:        https://bilat.xyz 

github:
  is_project_page: false

show_downloads: true
footer: © Copyright 2019 - <a href="mailto:lois@bilat.xyz">Loïs Bilat</a> - bilat.xyz
buttons:
  btn_1: true
  btn_2: true
  btn_3: false
  btn_4: false
  btn_5: false
  url_btn_1: http://bilat.xyz/cv
  url_btn_2: http://git.bilat.xyz
  url_btn_3: 
  text_btn_1: CV
  text_btn_2: GitHub
  text_btn_3:
